#!/bin/sh

start() {
    echo "Starting uav-control"
    start-stop-daemon --start --quiet --exec /usr/sbin/uav_control -- --daemonize
}
stop() {
    echo "Stopping uav-control"
    start-stop-daemon --stop --quiet --exec /usr/sbin/uav_control
}
restart() {
    stop
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?


