--- a/Makefile	2010-09-12 18:43:10.770000241 -0400
+++ b/Makefile	2010-09-12 18:28:04.766000243 -0400
@@ -12,9 +12,6 @@
 # $ sudo make DESTDIR=/some/path install
 DESTDIR = /usr/local
 
-# set the compiler to use
-CC = gcc
-
 # general compile flags, enable all warnings to make compile more verbose
 CFLAGS += -O2 -DLINUX -D_GNU_SOURCE -Wall
 #CFLAGS +=  -DDEBUG
@@ -22,7 +19,7 @@ CFLAGS += -O2 -DLINUX -D_GNU_SOURCE -Wal
 # we are using the libraries "libpthread" and "libdl"
 # libpthread is used to run several tasks (virtually) in parallel
 # libdl is used to load the plugins (shared objects) at runtime
-LFLAGS += -lpthread -ldl
+LFLAGS += -lpthread -ldl -Wl,--hash-style=gnu
 
 # define the name of the program
 APP_BINARY = mjpg_streamer
--- a/plugins/input_control/Makefile	2010-09-12 18:43:09.726000244 -0400
+++ b/plugins/input_control/Makefile	2010-09-12 18:30:51.847000225 -0400
@@ -7,12 +7,11 @@
 #
 ###############################################################
 
-CC = gcc
-
 OTHER_HEADERS = ../../mjpg_streamer.h ../../utils.h ../output.h ../input.h
 
 CFLAGS += -O2 -DLINUX -D_GNU_SOURCE -Wall -shared -fPIC
 #CFLAGS += -DDEBUG
+LFLAGS += -Wl,--hash-style=gnu
 
 all: input_control.so
 
--- a/plugins/input_file/Makefile	2010-09-12 18:43:10.470000248 -0400
+++ b/plugins/input_file/Makefile	2010-09-12 18:30:45.015000242 -0400
@@ -7,13 +7,11 @@
 #
 ###############################################################
 
-CC = gcc
-
 OTHER_HEADERS = ../../mjpg_streamer.h ../../utils.h ../output.h ../input.h
 
 CFLAGS += -O2 -DLINUX -D_GNU_SOURCE -Wall -shared -fPIC
 #CFLAGS += -DDEBUG
-LFLAGS += 
+LFLAGS += -Wl,--hash-style=gnu
 
 all: input_file.so
 
--- a/plugins/input_gspcav1/Makefile	2010-09-12 18:43:09.985000241 -0400
+++ b/plugins/input_gspcav1/Makefile	2010-09-12 18:31:59.676000236 -0400
@@ -7,13 +7,11 @@
 #
 ###############################################################
 
-CC = gcc
-
 OTHER_HEADERS = ../../mjpg_streamer.h ../../utils.h ../output.h ../input.h
 
 CFLAGS += -O2 -DLINUX -D_GNU_SOURCE -Wall -shared -fPIC
 #CFLAGS += -DDEBUG -O2 -DLINUX -D_GNU_SOURCE -Wall -shared -fPIC
-LFLAGS += -lpthread -ldl
+LFLAGS += -lpthread -ldl -Wl,--hash-style=gnu
 
 all: input_gspcav1.so
 
@@ -21,7 +19,7 @@ clean:
 	rm -f *.a *.o core *~ *.so *.lo
 
 input_gspcav1.so: $(OTHER_HEADERS) input_gspcav1.c spcav4l.lo utils.lo encoder.lo huffman.lo marker.lo quant.lo
-	$(CC) $(CFLAGS) -o $@ input_gspcav1.c spcav4l.lo utils.lo encoder.lo huffman.lo marker.lo quant.lo
+	$(CC) $(CFLAGS) $(LFLAGS) -o $@ input_gspcav1.c spcav4l.lo utils.lo encoder.lo huffman.lo marker.lo quant.lo
 
 spcav4l.lo:	spcav4l.c spcav4l.h
 	$(CC) -c $(CFLAGS) -o $@ $<
--- a/plugins/input_testpicture/Makefile	2010-09-12 18:43:10.349000242 -0400
+++ b/plugins/input_testpicture/Makefile	2010-09-12 18:32:54.778000260 -0400
@@ -7,8 +7,6 @@
 #
 ###############################################################
 
-CC = gcc
-
 OTHER_HEADERS = ../../mjpg_streamer.h ../../utils.h ../output.h ../input.h
 
 CFLAGS += -O2 -DLINUX -D_GNU_SOURCE -Wall -shared -fPIC
@@ -32,7 +30,7 @@ clean_pictures:
 	rm -f pictures/640x480_1.jpg pictures/640x480_2.jpg
 
 input_testpicture.so: $(OTHER_HEADERS) input_testpicture.c testpictures.h
-	$(CC) $(CFLAGS) -o $@ input_testpicture.c
+	$(CC) $(CFLAGS) $(LFLAGS) -o $@ input_testpicture.c
 
 # converts multiple JPG files to a single C header file
 testpictures.h: pictures/960x720_1.jpg pictures/640x480_1.jpg pictures/320x240_1.jpg pictures/160x120_1.jpg pictures/160x120_2.jpg pictures/320x240_2.jpg pictures/640x480_2.jpg pictures/960x720_2.jpg
--- a/plugins/input_uvc/Makefile	2010-09-12 18:43:10.467000228 -0400
+++ b/plugins/input_uvc/Makefile	2010-09-12 18:33:41.949000247 -0400
@@ -7,11 +7,10 @@
 #
 ###############################################################
 
-CC = gcc
-
 OTHER_HEADERS = ../../mjpg_streamer.h ../../utils.h ../output.h ../input.h
 
 CFLAGS += -O1 -DLINUX -D_GNU_SOURCE -Wall -shared -fPIC -g
+LFLAGS += -ljpeg -Wl,--hash-style=gnu
 
 ifeq ($(USE_LIBV4L2),true)
 LFLAGS += -lv4l2
--- a/plugins/output_autofocus/Makefile	2010-09-12 18:43:10.050000243 -0400
+++ b/plugins/output_autofocus/Makefile	2010-09-12 18:34:33.842000227 -0400
@@ -7,13 +7,11 @@
 #
 ###############################################################
 
-CC = gcc
-
 OTHER_HEADERS = ../../mjpg_streamer.h ../../utils.h ../output.h ../input.h
 
 #CFLAGS += -O2 -DLINUX -D_GNU_SOURCE -Wall -shared -fPIC
 CFLAGS += -DDEBUG -O2 -DLINUX -D_GNU_SOURCE -Wall -shared -fPIC
-LFLAGS += -lpthread -ldl
+LFLAGS += -lpthread -ldl -Wl,--hash-style=gnu
 
 all: output_autofocus.so
 
@@ -21,7 +19,7 @@ clean:
 	rm -f *.a *.o core *~ *.so *.lo
 
 output_autofocus.so: $(OTHER_HEADERS) output_autofocus.c processJPEG_onlyCenter.lo
-	$(CC) $(CFLAGS) -lm -o $@ output_autofocus.c processJPEG_onlyCenter.lo
+	$(CC) $(CFLAGS) $(LFLAGS) -lm -o $@ output_autofocus.c processJPEG_onlyCenter.lo
 
 processJPEG_onlyCenter.lo: $(OTHER_HEADERS) processJPEG_onlyCenter.h
 	$(CC) -c $(CFLAGS) -o $@ processJPEG_onlyCenter.c
--- a/plugins/output_file/Makefile	2010-09-12 18:43:09.758000241 -0400
+++ b/plugins/output_file/Makefile	2010-09-12 18:35:04.589000184 -0400
@@ -7,13 +7,11 @@
 #
 ###############################################################
 
-CC = gcc
-
 OTHER_HEADERS = ../../mjpg_streamer.h ../../utils.h ../output.h ../input.h
 
 CFLAGS += -O2 -DLINUX -D_GNU_SOURCE -Wall -shared -fPIC
 #CFLAGS += -DDEBUG
-LFLAGS += -lpthread -ldl
+LFLAGS += -lpthread -ldl -Wl,--hash-style=gnu
 
 all: output_file.so
 
@@ -21,4 +19,4 @@ clean:
 	rm -f *.a *.o core *~ *.so *.lo
 
 output_file.so: $(OTHER_HEADERS) output_file.c
-	$(CC) $(CFLAGS) -o $@ output_file.c
+	$(CC) $(CFLAGS) $(LFLAGS) -o $@ output_file.c
--- a/plugins/output_http/Makefile	2010-09-12 18:43:09.840000243 -0400
+++ b/plugins/output_http/Makefile	2010-09-12 18:35:35.892000243 -0400
@@ -7,13 +7,11 @@
 #
 ###############################################################
 
-CC = gcc
-
 OTHER_HEADERS = ../../mjpg_streamer.h ../../utils.h ../output.h ../input.h
 
 CFLAGS += -O1 -DLINUX -D_GNU_SOURCE -Wall -shared -fPIC -g
 #CFLAGS += -DDEBUG
-LFLAGS += -lpthread -ldl
+LFLAGS += -lpthread -ldl -Wl,--hash-style=gnu
 
 all: output_http.so
 
@@ -21,7 +19,7 @@ clean:
 	rm -f *.a *.o core *~ *.so *.lo
 
 output_http.so: $(OTHER_HEADERS) output_http.c httpd.lo
-	$(CC) $(CFLAGS) -o $@ output_http.c httpd.lo
+	$(CC) $(CFLAGS) $(LFLAGS) -o $@ output_http.c httpd.lo
 
 httpd.lo: $(OTHER_HEADERS) httpd.h httpd.c
 	$(CC) -c $(CFLAGS) -o $@ httpd.c
--- a/plugins/output_udp/Makefile	2010-09-12 18:43:10.114000243 -0400
+++ b/plugins/output_udp/Makefile	2010-09-12 18:36:22.963000235 -0400
@@ -9,13 +9,11 @@
 
 # Modified to work with the output_udp plugin by D.Zachariadis
 
-CC = gcc
-
 OTHER_HEADERS = ../../mjpg_streamer.h ../../utils.h ../output.h ../input.h
 
 CFLAGS += -O2 -DLINUX -D_GNU_SOURCE -Wall -shared -fPIC
 #CFLAGS += -DDEBUG
-LFLAGS += -lpthread -ldl
+LFLAGS += -lpthread -ldl -Wl,--hash-style=gnu
 
 all: output_udp.so
 
@@ -23,4 +21,4 @@ clean:
 	rm -f *.a *.o core *~ *.so *.lo
 
 output_udp.so: $(OTHER_HEADERS) output_udp.c
-	$(CC) $(CFLAGS) -o $@ output_udp.c
+	$(CC) $(CFLAGS) $(LFLAGS) -o $@ output_udp.c
--- a/plugins/output_viewer/Makefile	2010-09-12 18:43:09.874000243 -0400
+++ b/plugins/output_viewer/Makefile	2010-09-12 18:36:34.886000222 -0400
@@ -7,15 +7,13 @@
 #
 ###############################################################
 
-CC = gcc
-
 OTHER_HEADERS = ../../mjpg_streamer.h ../../utils.h ../output.h ../input.h
 
 CFLAGS += -O2 -DLINUX -D_GNU_SOURCE -Wall -shared -fPIC
 CFLAGS += -DUSE_SDL -I/usr/include/SDL
 #CFLAGS += -DDEBUG
 
-LFLAGS += -ljpeg -lSDL
+LFLAGS += -ljpeg -lSDL -Wl,--hash-style=gnu
 
 all: output_viewer.so
 
