#!/bin/sh

start() {
    echo "Starting pwm..."
    /sbin/modprobe pwm_module pwm_en=8,9,10,11
}
stop() {
    echo "Stopping pwm..."
    /sbin/modprobe -r pwm_module
}
restart() {
    stop
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?

